apiVersion: apps/v1
kind: Deployment
metadata:
  name: PreApplicationBC
  labels:
    app: PreApplicationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PreApplicationBC
  template:
    metadata:
      labels:
        app: PreApplicationBC
    spec:
      containers:
        - name: PreApplicationBC
          image: username/PreApplicationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5