apiVersion: apps/v1
kind: Deployment
metadata:
  name: IncomeVerificationBC
  labels:
    app: IncomeVerificationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IncomeVerificationBC
  template:
    metadata:
      labels:
        app: IncomeVerificationBC
    spec:
      containers:
        - name: IncomeVerificationBC
          image: username/IncomeVerificationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5