apiVersion: v1
kind: Service
metadata:
  name: IncomeVerificationBC
  labels:
    app: IncomeVerificationBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: IncomeVerificationBC