---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: PreApplicationBC
  labels:
    app: PreApplicationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PreApplicationBC
  template:
    metadata:
      labels:
        app: PreApplicationBC
    spec:
      containers:
        - name: PreApplicationBC
          image: username/PreApplicationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerRegistrationBC
  labels:
    app: CustomerRegistrationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerRegistrationBC
  template:
    metadata:
      labels:
        app: CustomerRegistrationBC
    spec:
      containers:
        - name: CustomerRegistrationBC
          image: username/CustomerRegistrationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: IncomeVerificationBC
  labels:
    app: IncomeVerificationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IncomeVerificationBC
  template:
    metadata:
      labels:
        app: IncomeVerificationBC
    spec:
      containers:
        - name: IncomeVerificationBC
          image: username/IncomeVerificationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AccountOpenBC
  labels:
    app: AccountOpenBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AccountOpenBC
  template:
    metadata:
      labels:
        app: AccountOpenBC
    spec:
      containers:
        - name: AccountOpenBC
          image: username/AccountOpenBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: NotifyBC
  labels:
    app: NotifyBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NotifyBC
  template:
    metadata:
      labels:
        app: NotifyBC
    spec:
      containers:
        - name: NotifyBC
          image: username/NotifyBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: PreApplicationBC
  labels:
    app: PreApplicationBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PreApplicationBC


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerRegistrationBC
  labels:
    app: CustomerRegistrationBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerRegistrationBC


---


apiVersion: v1
kind: Service
metadata:
  name: IncomeVerificationBC
  labels:
    app: IncomeVerificationBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: IncomeVerificationBC


---


apiVersion: v1
kind: Service
metadata:
  name: AccountOpenBC
  labels:
    app: AccountOpenBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AccountOpenBC


---


apiVersion: v1
kind: Service
metadata:
  name: NotifyBC
  labels:
    app: NotifyBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: NotifyBC

