apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerRegistrationBC
  labels:
    app: CustomerRegistrationBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerRegistrationBC
  template:
    metadata:
      labels:
        app: CustomerRegistrationBC
    spec:
      containers:
        - name: CustomerRegistrationBC
          image: username/CustomerRegistrationBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5