apiVersion: v1
kind: Service
metadata:
  name: CustomerRegistrationBC
  labels:
    app: CustomerRegistrationBC
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerRegistrationBC