apiVersion: apps/v1
kind: Deployment
metadata:
  name: AccountOpenBC
  labels:
    app: AccountOpenBC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AccountOpenBC
  template:
    metadata:
      labels:
        app: AccountOpenBC
    spec:
      containers:
        - name: AccountOpenBC
          image: username/AccountOpenBC:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5